apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: '2022-04-03T07:07:41+00:00'
  labels:
    io.kompose.service: db-claim0
  name: db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
