version: '3.4'

services:
  db:
    image: postgres
    #image: swipefund.azurecr.io/postgres # image for azure

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=swifi
      - POSTGRES_PASSWORD=swifi
    volumes:
      - ./sql/initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
      #- ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/lib/postgresql/data #storage option for azure
    #networks:
    #  - consumer-producer
  swipefundbackend:
    image: swipefund.azurecr.io/swipefundbackend
    domainname: 'swipefund'
    build:
      context: .
      dockerfile: ./Dockerfile
      #network: consumer-producer
    environment:
      PGHOST: db
      PGDATABASE: swifi
      PGUSERNAME: swifi
      PGPASSWORD: swifi
    ports:
      - '4000:4000'
    volumes:
      - './:/src'
    #networks:
    #  - consumer-producer
    depends_on:
      - db
    links:
      - db
#networks:
#  consumer-producer:
#    driver: bridge
volumes:
  db:
    driver: bridge
    #driver: azure_file #azure option
    #driver_opts:       #azure option
    #share_name: swipefund    #azure option
    #storage_account_name: swipefund    #azure option
# buildkit does not support custom networks
# start with "DOCKER_BUILDKIT=0 docker-compose up -d"
